name        = "dev/gitignore-node"
description = "Managed gitignore region for Node.js/npm projects"
params      = []
require     = ["dev/gitignore-base"]

[[file]]
src  = "files/.gitignore"
dest = ".gitignore"
mode = "region"
