name        = "flake-utils"
description = "a basic flake"
params      = ["nix-version", "packages"]
requires    = []

[[file]]
src  = "files/flake.nix"
dest = "flake.nix"
mode = "create"

[[file]]
src  = "files/.envrc"
dest = ".envrc"
mode = "region"
