name        = "dev/gitignore-logs"
description = "Managed gitignore region for log files"
params      = []
require     = ["dev/gitignore-base"]

[[file]]
src  = "files/.gitignore"
dest = ".gitignore"
mode = "region"
