name        = "license/mit"
description = "MIT licence"
params      = ["author", "current_year"]
fresh       = ["current_year"]

[param.author]
scope  = "profile"
prompt = "Your full name"

[[file]]
src  = "files/LICENSE"
dest = "LICENSE"
mode = "create"
