name        = "license/gpl-3.0"
description = "GNU General Public License v3.0"
params      = ["author", "current_year"]
fresh       = ["current_year"]

[param.author]
scope  = "profile"
prompt = "Your full name"

[[file]]
src  = "files/LICENSE"
dest = "LICENSE"
mode = "create"
