name        = "dev/gitignore-python"
description = "Append gitignore rules for Python projects"
params      = []
require     = ["dev/gitignore-base"]

[[file]]
src  = "files/.gitignore"
dest = ".gitignore"
mode = "append"
